### ISSUE TITLE
Configurable buffer length

### ISSUE THREAD

**Issue by miyagawa** [kazeburo/HTTP-Entity-Parser#3]
It would be good if we can configure the buffer length (8192) rather than hardcoded.

**Comment by kazeburo** [comment]
Okay, I do it.

**Comment by kazeburo** [comment]
Changed at 1142fd15e92294236b36a5b95e90c75ceee64fe5 and released HTTP::Entity::Parser 0.14

**Comment by miyagawa** [comment]
Any reason we can't configure it per Parser object? I mean it's reasonable to use pre-determined value per process, but the design of H::E::Parser allows customizing it in every object, because we initialize them in every Plack::Request load.

In Plack we'd probably make it an environment variable such as `PLACK_BUFFER_LENGTH`, but i don't see any reason we should make it a global variable in this module. 

Maybe we can make this global variable as a default value, then override in `new`?

**Comment by kazeburo** [comment]
No reason we can't configure buf_length per Parser object. I change it in next version.

**Comment by miyagawa** [comment]
Sounds good, not a big deal, but i thought it'd be nice to be able to change it in runtime - especially because we have requests with `psgix.input.buffered` which is all buffered already.

**Comment by kazeburo** [comment]
Just released HTTP::Entity::Parser 0.15
