### ISSUE TITLE
dechunk loop can stuck on empty chunked post 

### ISSUE THREAD

**Issue by PavelTrushkin** [kazeburo/HTTP-Entity-Parser#7]
original code is 
        DECHUNK: while(1) {
            $input->read(my $chunk, $buffer_length);

of course it will iterate forever on empty or malformed post chunked request

fix is easy
DECHUNK: while($input->read(my $chunk, $buffer_length)) {

also imho inner dechunking while is very very strange solution for potentially very large data - it copies data every $buffer_length bytes for large content

**Comment by kazeburo** [comment]
How about adding check buffer like these?

```
my $spin = 0;
DECHUNK: while(1) {
$input->read(my $chunk, $buffer_length);
my $read = length $chunk;
if ($read == 0 ) {
  Carp::croak "Malformed chunked request" if  $spin++ > 2000; 
  next;
}
$chunk_buffer .= $chunk;
while ( $chunk_buffer =~ s/^(([0-9a-fA-F]+).*\015\012)// ) {
```

**Comment by pippo** [comment]
I'd like to follow up on this.
@kazeburo Can the solution above be applied?
